apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
    #  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02d931b83d4d43939

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
    # namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
